Class MainWindow
    Private Sub Saltando_con_Doki_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/juego.swf", "Saltando con Doki/juego.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/common-gr.swf", "Saltando con Doki/common-gr.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/common-gr.swf", "Saltando con Doki/swf/common-gr.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/nivel1.swf", "Saltando con Doki/swf/nivel1.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/nivel2.swf", "Saltando con Doki/swf/nivel2.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/nivel3.swf", "Saltando con Doki/swf/nivel3.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/nivel4.swf", "Saltando con Doki/swf/nivel4.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-circulo.swf", "Saltando con Doki/swf/anim-circulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-cruz.swf", "Saltando con Doki/swf/anim-cruz.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-cuadrado.swf", "Saltando con Doki/swf/anim-cuadrado.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-estrella.swf", "Saltando con Doki/swf/anim-estrella.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-ovalo.swf", "Saltando con Doki/swf/anim-ovalo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-rectangulo.swf", "Saltando con Doki/swf/anim-rectangulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-rombo.swf", "Saltando con Doki/swf/anim-rombo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/swf/anim-triangulo.swf", "Saltando con Doki/swf/anim-triangulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/bostezo_snd.mp3", "Saltando con Doki/sonidos/bostezo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/esfuma_snd.mp3", "Saltando con Doki/sonidos/esfuma_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/musica_snd.mp3", "Saltando con Doki/sonidos/musica_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/objetivo_snd.mp3", "Saltando con Doki/sonidos/objetivo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/paso1_snd.mp3", "Saltando con Doki/sonidos/paso1_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/paso2_snd.mp3", "Saltando con Doki/sonidos/paso2_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/pestaneo_snd.mp3", "Saltando con Doki/sonidos/pestaneo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/plataforma1_snd.mp3", "Saltando con Doki/sonidos/plataforma1_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/plataforma2_snd.mp3", "Saltando con Doki/sonidos/plataforma2_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/plataforma3_snd.mp3", "Saltando con Doki/sonidos/plataforma3_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/plataforma4_snd.mp3", "Saltando con Doki/sonidos/plataforma4_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/saltando-con-doki/sonidos/salto_snd.mp3", "Saltando con Doki/sonidos/salto_snd.mp3")
    End Sub
    Private Sub Doki_y_los_Alimentos_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-los-alimentos/swf/juego.swf", "Doki y los Alimentos/swf/juego.swf")
    End Sub
    Private Sub Doki_e_os_Alimentos_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/doki-e-os-alimentos/swf/juego.swf", "Doki e os Alimentos/swf/juego.swf")
    End Sub

    Private Sub Pulando_com_Doki_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/juego.swf", "Pulando com Doki/juego.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/common-gr.swf", "Pulando com Doki/common-gr.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/common-gr.swf", "Pulando com Doki/swf/common-gr.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/nivel1.swf", "Pulando com Doki/swf/nivel1.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/nivel2.swf", "Pulando com Doki/swf/nivel2.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/nivel3.swf", "Pulando com Doki/swf/nivel3.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/nivel4.swf", "Pulando com Doki/swf/nivel4.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-circulo.swf", "Pulando com Doki/swf/anim-circulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-cruz.swf", "Pulando com Doki/swf/anim-cruz.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-cuadrado.swf", "Pulando com Doki/swf/anim-cuadrado.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-estrella.swf", "Pulando com Doki/swf/anim-estrella.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-ovalo.swf", "Pulando com Doki/swf/anim-ovalo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-rectangulo.swf", "Pulando com Doki/swf/anim-rectangulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-rombo.swf", "Pulando com Doki/swf/anim-rombo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/swf/anim-triangulo.swf", "Pulando com Doki/swf/anim-triangulo.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/bostezo_snd.mp3", "Pulando com Doki/sonidos/bostezo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/esfuma_snd.mp3", "Pulando com Doki/sonidos/esfuma_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/musica_snd.mp3", "Pulando com Doki/sonidos/musica_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/objetivo_snd.mp3", "Pulando com Doki/sonidos/objetivo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/paso1_snd.mp3", "Pulando com Doki/sonidos/paso1_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/paso2_snd.mp3", "Pulando com Doki/sonidos/paso2_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/pestaneo_snd.mp3", "Pulando com Doki/sonidos/pestaneo_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/plataforma1_snd.mp3", "Pulando com Doki/sonidos/plataforma1_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/plataforma2_snd.mp3", "Pulando com Doki/sonidos/plataforma2_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/plataforma3_snd.mp3", "Pulando com Doki/sonidos/plataforma3_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/plataforma4_snd.mp3", "Pulando com Doki/sonidos/plataforma4_snd.mp3")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/pulando-com-doki/sonidos/salto_snd.mp3", "Pulando com Doki/sonidos/salto_snd.mp3")
    End Sub
    Private Sub Habitos_y_Nutricion_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/creciendo-sanos/swf/index_es.swf", "Hábitos y Nutrición/swf/index_es.swf")
    End Sub
    Private Sub El_Juego_de_las_Emociones_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/el-juego-de-las-emociones/swf/game.swf", "El Juego de las Emociones/swf/game.swf")
    End Sub

    Private Sub Ordenando_los_Planetas_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/ordenando-los-planetas/swf/juego.swf", "Ordenando los Planetas/swf/juego.swf")
    End Sub
    Private Sub Ordenando_os_Planetas_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/ordenando-os-planetas/swf/juego.swf", "Ordenando os Planetas/swf/juego.swf")
    End Sub
    Private Sub Contando_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/contando/swf/FinalContando.swf", "Contando/swf/FinalContando.swf")
    End Sub
    Private Sub Tu_Cuerpo_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/tu_cuerpo_intro.swf", "Tu Cuerpo/swf/tu_cuerpo_intro.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/interactivo_nena.swf", "Tu Cuerpo/swf/interactivo_nena.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/interactivo_nene.swf", "Tu Cuerpo/swf/interactivo_nene.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_corazon.swf", "Tu Cuerpo/swf/sabias_corazon.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_corazon.swf", "Tu Cuerpo/swf/main_corazon.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_cerebro.swf", "Tu Cuerpo/swf/sabias_cerebro.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_cerebro.swf", "Tu Cuerpo/swf/main_cerebro.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_pulmones.swf", "Tu Cuerpo/swf/sabias_pulmones.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_pulmones.swf", "Tu Cuerpo/swf/main_pulmones.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_rinones.swf", "Tu Cuerpo/swf/sabias_rinones.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_rinones.swf", "Tu Cuerpo/swf/main_rinones.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_estomago.swf", "Tu Cuerpo/swf/sabias_estomago.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_estomago.swf", "Tu Cuerpo/swf/main_estomago.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_intestino.swf", "Tu Cuerpo/swf/sabias_intestino.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_intestino.swf", "Tu Cuerpo/swf/main_intestino.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_esqueleto.swf", "Tu Cuerpo/swf/sabias_esqueleto.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_esqueleto.swf", "Tu Cuerpo/swf/main_esqueleto.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/sabias_musculos.swf", "Tu Cuerpo/swf/sabias_musculos.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/cuerpo-humano/swf/main_musculos.swf", "Tu Cuerpo/swf/main_musculos.swf")
    End Sub
    Private Sub A_Viajar_con_Carlitos_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/motor.swf", "A Viajar con Carlitos/swf/motor.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/idiomas/espanol.txt", "A Viajar con Carlitos/idiomas/espanol.txt")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/intro.swf", "A Viajar con Carlitos/swf/intro.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/respuesta.swf", "A Viajar con Carlitos/swf/respuesta.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/pregunta1.swf", "A Viajar con Carlitos/swf/pregunta1.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/pregunta2.swf", "A Viajar con Carlitos/swf/pregunta2.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/pregunta3.swf", "A Viajar con Carlitos/swf/pregunta3.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/a-viajar-con-carlitos/swf/pregunta4.swf", "A Viajar con Carlitos/swf/pregunta4.swf")
    End Sub
    Private Sub Aprendiendo_Melodias_con_Doki_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/aprendiendo-melodias/swf/melodias.swf", "Aprendiendo Melodías con Doki/swf/melodias.swf")
    End Sub
    Private Sub Aprendendo_Melodias_com_Doki_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/aprendendo-melodias/swf/melodias.swf", "Aprendendo Melodias com Doki/swf/melodias.swf")
    End Sub
    Private Sub Astrodoki_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/astrodoki/cargarespacio.swf", "Astrodoki/cargarespacio.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/astrodoki/espacio.swf", "Astrodoki/espacio.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/astrodoki/niveles.xml", "Astrodoki/niveles.xml")
    End Sub
    Private Sub Astrodoki_Portuguese_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/astrodoki/cargarespacio.swf", "Astrodoki (Portuguese)/cargarespacio.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/astrodoki/espacio.swf", "Astrodoki (Portuguese)/espacio.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/portugues/doki/astrodoki/niveles.xml", "Astrodoki (Portuguese)/niveles.xml")
    End Sub
    Private Sub Doki_y_el_Arbol_de_Mango_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-el-arbol/swf/dokiloadere.swf", "Doki y el Árbol de Mango/swf/dokiloadere.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-el-arbol/swf/cuentodoki.swf", "Doki y el Árbol de Mango/swf/cuentodoki.swf")
    End Sub
    Private Sub Don_Cangrejito_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/cangrejito.swf", "Don Cangrejito/cangrejito.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina_blanco.swf", "Don Cangrejito/pagina_blanco.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina1.swf", "Don Cangrejito/pagina1.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina2.swf", "Don Cangrejito/pagina2.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina3.swf", "Don Cangrejito/pagina3.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina4.swf", "Don Cangrejito/pagina4.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina5.swf", "Don Cangrejito/pagina5.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/don-cangrejito/pagina6.swf", "Don Cangrejito/pagina6.swf")
    End Sub
    Private Sub Laberinto_Pregunton_2_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/laberinto-pregunton-2/swf/laberinto.swf", "Laberinto Preguntón 2/swf/laberinto.swf")
    End Sub
    Private Sub Laberinto_Pregunton_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/variados/laberinto-pregunton/swf/laberinto.swf", "Laberinto Preguntón/swf/laberinto.swf")
    End Sub
    Private Sub Doki_y_sus_globos_magicos_Selected(sender As Object, e As RoutedEventArgs)
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-sus-globos-magicos/swf/motor.swf", "Doki y sus globos mágicos/swf/motor.swf")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-sus-globos-magicos/txt/dk_config.txt", "Doki y sus globos mágicos/txt/dk_config.txt")
        My.Computer.Network.DownloadFile("https://juegos-secure.discoverykidsplus.com/shared_content/custom-games/games/espaniol/doki/doki-y-sus-globos-magicos/txt/dk_genericos.txt", "Doki y sus globos mágicos/txt/dk_genericos.txt")
    End Sub
    Private Sub ComboBox_SelectionChanged(sender As Object, e As SelectionChangedEventArgs)

    End Sub
End Class
